const fishs = [
    {
        fishid:1,
        fish_pic:'../asset/fish/pic/fish_pic1.png',
        fish_data:'../asset/fish/data/fish_data1.png'
    },
    {
        fishid:2,
        fish_pic:'../asset/fish/pic/fish_pic2.png',
        fish_data:'../asset/fish/data/fish_data2.png'
    },
    {
        fishid:3,
        fish_pic:'../asset/fish/pic/fish_pic3.png',
        fish_data:'../asset/fish/data/fish_data3.png'
    },
    {
        fishid:4,
        fish_pic:'../asset/fish/pic/fish_pic4.png',
        fish_data:'../asset/fish/data/fish_data4.png'
    },
    {
        fishid:5,
        fish_pic:'../asset/fish/pic/fish_pic5.png',
        fish_data:'../asset/fish/data/fish_data5.png'
    },
    {
        fishid:6,
        fish_pic:'../asset/fish/pic/fish_pic6.png',
        fish_data:'../asset/fish/data/fish_data6.png'
    },
    {
        fishid:7,
        fish_pic:'../asset/fish/pic/fish_pic7.png',
        fish_data:'../asset/fish/data/fish_data7.png'
    },
    {
        fishid:8,
        fish_pic:'../asset/fish/pic/fish_pic8.png',
        fish_data:'../asset/fish/data/fish_data8.png'
    },
    {
        fishid:9,
        fish_pic:'../asset/fish/pic/fish_pic9.png',
        fish_data:'../asset/fish/data/fish_data9.png'
    },
    {
        fishid:10,
        fish_pic:'../asset/fish/pic/fish_pic10.png',
        fish_data:'../asset/fish/data/fish_data10.png'
    },
    {
        fishid:11,
        fish_pic:'../asset/fish/pic/fish_pic11.png',
        fish_data:'../asset/fish/data/fish_data11.png'
    },
    {
        fishid:12,
        fish_pic:'../asset/fish/pic/fish_pic12.png',
        fish_data:'../asset/fish/data/fish_data12.png'
    },
    {
        fishid:13,
        fish_pic:'../asset/fish/pic/fish_pic13.png',
        fish_data:'../asset/fish/data/fish_data13.png'
    }
]